name: Tweet new RSS Feed items FWTV	
on:
  rss:
    url: 
      - https://www.oostende.be/nieuws/rss
jobs:
  twitter:
    name: Post a tweet
    runs-on: ubuntu-latest
    steps:
      - name: Post a tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ on.rss.outputs.title }} ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
