name: Tweet new RSS Feed items FWTV	
on:
  rss:
    url: 
      - http://www.nieuwsblad.be/rss/section/bf9eeee6-51e0-49e8-ad4a-791dcc2f63ae?intro=1
jobs:
  twitter:
    name: Post a tweet
    runs-on: ubuntu-latest
    steps:
      - name: Post a tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ on.rss.outputs.title }} ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
